### ISSUE TITLE
关于lastUpdated的问题

### ISSUE THREAD

**Issue by C01day** [Renovamen/blog.zxh.io#20]
你好，我发现博客的lastUpdated好像都是一个值

**Comment by Renovamen** [comment]
好的，谢谢。我在本地测试的时候是没问题的，所以我猜是我用 github action 自动部署的时候，它直接强制把所有文件的 commit 时间都洗成最近一次的 commit 时间了...

**Comment by C01day** [comment]
好的，谢谢。我之后也尝试一下github action
